In [1]:
import numpy as np

In [2]:
vector = np.array([2, 4, 6, 8, 10])

# zeros and ones
zeros_matrix = np.zeros((3, 2))
ones_matrix = np.ones((2, 4))

# ranges
even_numbers = np.arange(1, 12, 2)        # 1, 3, 5, 7, 9, 11
linear_space = np.linspace(-1, 1, 7)      # 7 точек от -1 до 1

print("vector:", vector)
print("zeros_matrix:\n", zeros_matrix)
print("ones_matrix:\n", ones_matrix)
print("even_numbers:", even_numbers)
print("linear_space:", linear_space)


vector: [ 2  4  6  8 10]
zeros_matrix:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones_matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
even_numbers: [ 1  3  5  7  9 11]
linear_space: [-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.        ]


In [3]:
print("vector -> shape:", vector.shape, "| dtype:", vector.dtype, "| ndim:", vector.ndim)
print("zeros_matrix -> shape:", zeros_matrix.shape, "| dtype:", zeros_matrix.dtype, "| ndim:", zeros_matrix.ndim)

float_array = np.array([0.1, 0.5, 1.5])
print("float_array -> shape:", float_array.shape, "| dtype:", float_array.dtype, "| ndim:", float_array.ndim)


vector -> shape: (5,) | dtype: int64 | ndim: 1
zeros_matrix -> shape: (3, 2) | dtype: float64 | ndim: 2
float_array -> shape: (3,) | dtype: float64 | ndim: 1


In [4]:
arr = np.arange(15)  # [0 1 2 ... 14]

print("arr:", arr)
print("first element:", arr[0])
print("third element:", arr[2])
print("last element:", arr[-1])

print("slice 3:10:", arr[3:10])
print("every third element:", arr[::3])
print("middle part (5:12):", arr[5:12])


arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
first element: 0
third element: 2
last element: 14
slice 3:10: [3 4 5 6 7 8 9]
every third element: [ 0  3  6  9 12]
middle part (5:12): [ 5  6  7  8  9 10 11]


In [5]:
matrix = np.arange(1, 17).reshape(4, 4)
print("matrix:\n", matrix)

print("element matrix[1, 2]:", matrix[1, 2])     # вторая строка, третий столбец
print("first row:", matrix[0, :])
print("last column:", matrix[:, -1])
print("submatrix rows 1:3, cols 0:2:\n", matrix[1:3, 0:2])


matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
element matrix[1, 2]: 7
first row: [1 2 3 4]
last column: [ 4  8 12 16]
submatrix rows 1:3, cols 0:2:
 [[ 5  6]
 [ 9 10]]


In [6]:
x = np.array([3, 6, 9, 12])
y = np.array([1, 2, 3, 4])

print("x:", x)
print("y:", y)

print("x + y:", x + y)
print("x - y:", x - y)
print("x * y:", x * y)
print("x squared:", x ** 2)

print("mean of x:", x.mean())
print("sum of x:", x.sum())
print("max of x:", x.max())
print("min of x:", x.min())

matrix2 = np.arange(1, 10).reshape(3, 3)
print("matrix2:\n", matrix2)
print("matrix2 mean:", matrix2.mean())
print("row-wise sums:", matrix2.sum(axis=1))
print("column-wise sums:", matrix2.sum(axis=0))


x: [ 3  6  9 12]
y: [1 2 3 4]
x + y: [ 4  8 12 16]
x - y: [2 4 6 8]
x * y: [ 3 12 27 48]
x squared: [  9  36  81 144]
mean of x: 7.5
sum of x: 30
max of x: 12
min of x: 3
matrix2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix2 mean: 5.0
row-wise sums: [ 6 15 24]
column-wise sums: [12 15 18]
